apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authorization-service
  name: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: quay.io/phagen/authorization-service:1.4.1
        imagePullPolicy: Always
        name: authorization-service
        env:
          - name: NODE_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name:  OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: OTEL_SERVICE_NAME
            value: "Authorization-service"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"